---
# 检测并安装keepalived和haproxy

# 检测keepalived是否已安装
- name: Check if keepalived is installed
  command: rpm -q keepalived
  register: keepalived_check
  failed_when: false  # 即使命令失败（未安装）也不视为任务失败
  changed_when: false

# 检测haproxy是否已安装
- name: Check if haproxy is installed
  command: rpm -q haproxy
  register: haproxy_check
  failed_when: false
  changed_when: false

# 安装keepalived（仅当未安装时）
- name: Install keepalived if not present
  dnf:
    name: keepalived
    state: present
  when: keepalived_check.rc != 0  # rc为0表示已安装，非0表示未安装

# 安装haproxy（仅当未安装时）
- name: Install haproxy if not present
  dnf:
    name: haproxy
    state: present
  when: haproxy_check.rc != 0

# 确保服务启动并设置开机自启（无论安装状态，确保服务状态正确）
- name: Ensure keepalived service is running and enabled
  systemd:
    name: keepalived
    state: started
    enabled: yes

- name: Ensure haproxy service is running and enabled
  systemd:
    name: haproxy
    state: started
    enabled: yes
