apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
# Grafana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:9.5.2
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-config
              mountPath: /etc/grafana/provisioning/datasources
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"  # 初始管理员密码，生产环境建议修改
            - name: GF_USERS_ALLOW_SIGN_UP
              value: "false"  # 禁用注册功能
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-config
          configMap:
            name: grafana-datasources
---
# Grafana 数据源配置
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090  # 关联Prometheus Service
      access: proxy
      isDefault: true
---
# Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP  # 如需外部访问可改为NodePort或LoadBalancer
---
# 可选：Grafana 控制台仪表盘配置（Kubernetes监控面板）
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
data:
  k8s-cluster-dashboard.json: |
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": {
              "type": "datasource",
              "uid": "grafana"
            },
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": 1,
      "iteration": 1696144218437,
      "links": [],
      "panels": [],
      "refresh": "10s",
      "schemaVersion": 38,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": []
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Kubernetes Cluster Monitoring",
      "uid": "k8s-cluster",
      "version": 1
    }
---
# 可选：部署仪表盘加载器
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dashboard-loader
  namespace: monitoring
  labels:
    app: grafana-dashboard-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dashboard-loader
  template:
    metadata:
      labels:
        app: grafana-dashboard-loader
    spec:
      containers:
        - name: loader
          image: busybox:1.35
          command: ["/bin/sh", "-c"]
          args:
            - |
              # 等待Grafana就绪
              until wget -q --spider http://grafana:3000; do
                sleep 5
              done
              # 导入仪表盘配置
              wget -O /tmp/dashboard.json /etc/dashboards/k8s-cluster-dashboard.json
              curl -X POST -H "Content-Type: application/json" -u admin:admin \
                -d @/tmp/dashboard.json http://grafana:3000/api/dashboards/db
              # 保持容器运行
              tail -f /dev/null
          volumeMounts:
            - name: dashboard-config
              mountPath: /etc/dashboards
      volumes:
        - name: dashboard-config
          configMap:
            name: grafana-dashboards
