---
- name: 创建临时目录存放 Prometheus 镜像
  file:
    path: "/tmp/prometheus"
    state: directory
    mode: '0755'

- name: 复制 Prometheus 镜像到目标节点
  copy:
    src: "{{ playbook_dir }}/images/{{ item }}"
    dest: "/tmp/prometheus/{{ item }}"
    mode: 0644
    directory_mode: 0755           # 为目录设置单独的权限（可选）
    remote_src: no         # 表示src是本地路径，不是远程路径
    force: yes             # 如果目标存在则覆盖
  with_items:
    - "prometheus-v2.45.0.tar"
    - "node-exporter-v1.6.1.tar"
    - "grafana-9.5.2.tar"
    - "kube-state-metrics-v2.9.2.tar"
    - "alertmanager-v0.25.0.tar"
    - "jimmidyson-configmap-reload-v0.8.0.tar"
    - "busybox-1.35.0.tar"

- name: 加载 Prometheus 镜像到 Docker
  shell: "docker load -i /tmp/prometheus/{{ item }}"
  with_items:
    - "prometheus-v2.45.0.tar"
    - "node-exporter-v1.6.1.tar"
    - "grafana-9.5.2.tar"
    - "kube-state-metrics-v2.9.2.tar"
    - "alertmanager-v0.25.0.tar"
    - "jimmidyson-configmap-reload-v0.8.0.tar"
    - "busybox-1.35.0.tar"
