---
- name: Install kubeadm kubelet
  dnf: 
    name: 
      - kubeadm
      - kubelet
      - cri-tools
    state: present
  when: is_worker == 1



# 新增任务：加载本地Kubernetes镜像
- name: 复制本地镜像文件到目标节点
  copy:
    src: "{{ playbook_dir }}/images/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: 0644
  with_items:
    - "kube-apiserver-v1.29.3.tar"
    - "kube-controller-manager-v1.29.3.tar"
    - "kube-scheduler-v1.29.3.tar"
    - "kube-proxy-v1.29.3.tar"
    - "pause-3.9.tar"
    - "etcd-3.5.16-0.tar"
    - "coredns-v1.11.1.tar"
  when: is_worker == 1  # 所有节点都需要加载

- name: 加载本地镜像到Docker
  shell: "docker load -i /tmp/{{ item }}"
  with_items:
    - "kube-apiserver-v1.29.3.tar"
    - "kube-controller-manager-v1.29.3.tar"
    - "kube-scheduler-v1.29.3.tar"
    - "kube-proxy-v1.29.3.tar"
    - "pause-3.9.tar"
    - "etcd-3.5.16-0.tar"
    - "coredns-v1.11.1.tar"
  when: is_worker == 1  # 所有节点都需要加载

# 为镜像打官方标签（kubeadm仅识别官方标签）
- name: 为镜像打官方标签 (k8s.gcr.io)
  shell: |
    docker tag \
      {{ image_repository }}/{{ item.name }}:{{ item.tag }} \
      k8s.gcr.io/{{ item.target }}:{{ item.tag }}
  loop:
    - { name: "kube-apiserver", target: "kube-apiserver", tag: "v1.29.3" }
    - { name: "kube-controller-manager", target: "kube-controller-manager", tag: "v1.29.3" }
    - { name: "kube-scheduler", target: "kube-scheduler", tag: "v1.29.3" }
    - { name: "kube-proxy", target: "kube-proxy", tag: "v1.29.3" }
    - { name: "pause", target: "pause", tag: "3.9" }
    - { name: "etcd", target: "etcd", tag: "3.5.16-0" }
    - { name: "coredns", target: "coredns", tag: "v1.11.1" }  # coredns镜像名特殊处理

- name: Install kubectl
  dnf: 
    name: kubectl
    state: present
  when: is_master == 1

- name: Kubelet configuration
  copy: 
    src: kubelet
    dest: /etc/sysconfig/kubelet
  when: is_worker == 1

- name: Enable kubelet
  systemd: 
    name: kubelet.service
    enabled: yes
  when: is_worker == 1
  notify:
    - Restart OS
    - Wait for server come back

- name: Flush handlers
  meta: flush_handlers

