---
- name: Clean existing repodata
  file:
    path: "{{ playbook_dir }}/repo/packages/repodata"
    state: absent
  when: (is_init is defined) and (is_init == 1)

- name: Generate repository metadata
  shell: createrepo --database {{ playbook_dir }}/repo/packages/
  when: (is_init is defined) and (is_init == 1)

- name: 复制整个repo目录到各节点的/home目录
  copy:
    src: "{{ playbook_dir }}/repo"  # 源目录
    dest: "/home/"                  # 目标父目录
    mode: 0644
    directory_mode: 0755           # 为目录设置单独的权限（可选）
    remote_src: no         # 表示src是本地路径，不是远程路径
    force: yes             # 如果目标存在则覆盖
  when: is_worker == 1  # 所有节点都需要加载

- name: Delete existed files in directory
  file: 
    path: /etc/yum.repos.d
    mode: 0755
    state: "{{ item }}"
  loop:
    - absent
    - directory

- name: Remove existing local.repo if present
  file:
    path: /etc/yum.repos.d/local.repo
    state: absent

- name: Remove existing openEuler.repo if present
  file:
    path: /etc/yum.repos.d/openEuler.repo
    state: absent

- name: Get repo file - local.repo
  copy:
    src: "local.repo"
    dest: "/etc/yum.repos.d/local.repo"



- name: 执行 yum makecache 更新缓存
  yum:
      update_cache: yes
  register: yum_result
  retries: 3  # 重试3次，防止网络临时问题
  delay: 5    # 每次重试间隔5秒
  until: yum_result is succeeded